export const START_EDIT = 'TABLES/START_EDIT';
export const END_EDIT = 'TABLES/END_EDIT';
export const SET_DATA = 'TABLES/SET_DATA';
export const UPDATE_DATA = 'TABLES/UPDATE_DATA';
export const CREATE_ROW = 'TABLES/CREATE_ROW';
export const ADD_ROW = 'TABLES/ADD_ROW';
export const EDIT_ROW = 'TABLES/EDIT_ROW';
export const DELETE_ROWS = 'TABLES/DELETE_ROWS';
export const CANCEL = 'TABLES/CANCEL';
export const SAVE = 'TABLES/SAVE';
export const SELECT_ROW = 'TABLES/SELECT_ROW';
export const SELECT_ALL_ROWS = 'TABLES/SELECT_ALL_ROWS';
export const UNSELECT_ROW = 'TABLES/UNSELECT_ROW';
export const UNSELECT_ALL_ROWS = 'TABLES/UNSELECT_ALL_ROWS';
export const SET_ALL_ERRORS = 'TABLES/SET_ALL_ERRORS';
export const SELECT_ONLY_ONE_ROW = 'TABLES/SELECT_ONLY_ONE_ROW';
export const SET_ALL_LINES_ERRORS = 'TABLES/SET_ALL_LINES_ERRORS';
export const SET_ERRORS = 'TABLES/SET_ERRORS';
export const SET_PAGINATION = 'TABLES/SET_PAGINATION';
export const SET_TRANSFORMED_TABLE_DATA = 'TABLES/SET_TRANSFORMED_TABLE_DATA';
export const GET_DATA_ATTEMPT = 'TABLES/GET_DATA_ATTEMPT';
export const SET_TABLE_DISABILITY = 'TABLES/SET_TABLE_DISABILITY';
export const REMOVE_TABLE = 'TABLES/REMOVE_TABLE';
export const SET_VISIBLE = 'TABLES/SET_VISIBLE';
export const SORT_TABLE = 'TABLES/SORT_TABLE';
export const CREATE_ITEM = 'TABLES/CREATE_ITEM';

export const TABLESENUM = {
  AXISES: 'axises',
  SECTIONS: 'sections',
  ACCOUNT_RESULTS: 'accountResults',
  BALANCE_SHEET: 'balanceSheet'
};
