export const SET_CURRENT_FORM = 'form/SET_CURRENT_FORM';
export const UPDATE_CURRENT_FORM_DATA = 'form/UPDATE_CURRENT_FORM_DATA';
export const CLOSE_CURRENT_FORM = 'form/CLOSE_CURRENT_FORM';
export const QUIT_CURRENT_FORM = 'form/QUIT_CURRENT_FORM';
